spring.application.name=delivery-service
server.port=8086

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=delivery_service_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=FoodOrder@12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
jwt.secret=FoodOrderingSystemSuperSecretKeyFoodOrderingSystemSuperSecretKey123456